export type { PropsIcono } from "./tipos";
export { IconoBeneficio } from "./IconoBeneficio";
export { IconoUsuario } from "./IconoUsuario";
export { IconoCarrito } from "./IconoCarrito";
export { IconoMenu } from "./IconoMenu";
export { IconoPedidos } from "./IconoPedidos";
export { IconoSol } from "./IconoSol";
export { IconoLuna } from "./IconoLuna";
export { IconoSearch } from "./IconoSearch";
export { IconoUbicacion } from "./IconoUbicacion";
export { IconoChevronAbajo } from "./IconoChevronAbajo";
export { IconoFlechaAbajo } from "./IconoFlechaAbajo";
export { IconoEtiqueta } from "./IconoEtiqueta";
export { IconoPregunta } from "./IconoPregunta";
export { IconoMoneda } from "./IconoMoneda";
export { IconoMarca } from "./IconoMarca";
export { IconoTicket } from "./IconoTicket";
